### PR TITLE
Install `ebtel++` on CI

### PR DESCRIPTION
**Pull request by wtbarnes**
This PR does two things:

1. Pulls the path to `ebtel++` from an environment variable `EBTELPLUSPLUS_DIR`
2. Adds a few steps in the GH Actions script to install `ebtel++` on the CI

This may require a bit of debugging.

### CODE REVIEW

**Comment by jwreep** [comment]
Thanks, Will!  Looks good to me, so I hope this works.  Once it's merged on the main ebtel++ repository, we'll have to remember to update the repository it pulls here.

**Comment by wtbarnes** [comment]
Thanks for fixing my bad `cd`. It looks like the CI is now failing for a different reason that I don't fully understand. It appears to be somewhere in `showyourwork`.

**Comment by jwreep** [comment]
The current issue is a Snakemake warning.  I had this issue previously when compiling manually on my computer, but thought I solved it with the environment files.  It still works fine on my computer, so don't know why the CI is having an issue.  I tried adding an explicit call to set the priority to strict, but it didn't work.

**Comment by jwreep** [comment]
Well, it's building now -- so long as the OrcIDs are commented out.  (I suppose I could fork showyourwork and fix the problematic line to get it to build with OrcIDs . . . maybe later.)

Thank you for the help with this!

**Pull request merged**
